name: CPP homework tests

on:
  push:
    branches:
      - hw*

env:
  # CMake build type: Release, Debug, RelWithDebInfo
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - name: check out code
        uses: actions/checkout@v3

      - name: configure CMake
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: CMake build
        run: cmake --build build --config $BUILD_TYPE

      - name: run unit tests
        run: |
          ctest --test-dir build -C $BUILD_TYPE -VV

      